name: Release Build
on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      rebuild:
        description: 'A tag name for building previously created release'
        required: false
        default: '0.0.0'
      buildOptions:
        description: 'Additional options for Gradle build command'
        required: false
        default: ''

jobs:
  release:
    concurrency: release
    runs-on: ubuntu-latest
    outputs:
      version: ${{steps.get-version.outputs.version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check version
        id: get-version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          if [[ -n "${{ github.event.inputs.buildOptions }}" ]]
            then
              VERSION="${{ github.event.inputs.buildOptions }}"
          fi
          echo ::set-output name=version::${VERSION}
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_GITHUB }}
      - name: Test and build the image
        env:
          GENERATE_SOURCEMAP: false
          CI: false
        run: ./gradlew test jib ${{ github.event.inputs.buildOptions }} --no-daemon --scan --image ghcr.io/hellices/odd-platform -Pversion=${{ steps.get-version.outputs.version }} -PcontainerBuildArm=true -PcontainerBuildAmd=true
